# http://goreleaser.com
release:
  github:
    owner: markruler
    name: swage
  prerelease: false

env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy
    # - go generate ./...

builds:
  - binary: swage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - 386
      # - arm64
    ldflags:
      - -s -w -extldflags='-static' -X github.com/markruler/swage/pkg/cmd.swageVersion={{ .Tag }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64 # 64-bit
      # 386: i386 # 32-bit
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Tag }}_checksums'

changelog:
  sort: asc
  filters:
    exclude:
    - docs
    - test
    - typo
    - Merge pull request
    - Merge branch
